version: "3"

services:
  r:
    build: .
    privileged: true
    environment:
      DISPLAY: ${DISPLAY}
    volumes:
      - .:/app
      - renv-cache:/renv/cache
      - ~/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix

volumes:
  renv-cache:
